/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AskRouteImport } from './routes/ask'
import { Route as ContributeRouteImport } from './routes/contribute'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as HomeRouteImport } from './routes/home'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as MapRouteImport } from './routes/map'
import { Route as MediaRouteImport } from './routes/media'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ExpeditionsIndexRouteImport } from './routes/expeditions.index'
import { Route as ExpeditionsIdRouteImport } from './routes/expeditions.$id'
import { Route as ItemIdRouteImport } from './routes/item.$id'
import { Route as JourneyIdRouteImport } from './routes/journey.$id'
import { Route as StationsIndexRouteImport } from './routes/stations.index'
import { Route as StationsIdRouteImport } from './routes/stations.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeRoute = ContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpeditionsIndexRoute = ExpeditionsIndexRouteImport.update({
  id: '/expeditions/',
  path: '/expeditions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpeditionsIdRoute = ExpeditionsIdRouteImport.update({
  id: '/expeditions/$id',
  path: '/expeditions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemIdRoute = ItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyIdRoute = JourneyIdRouteImport.update({
  id: '/journey/$id',
  path: '/journey/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StationsIndexRoute = StationsIndexRouteImport.update({
  id: '/stations/',
  path: '/stations/',
  getParentRoute: () => rootRouteImport,
} as any)
const StationsIdRoute = StationsIdRouteImport.update({
  id: '/stations/$id',
  path: '/stations/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ask': typeof AskRoute
  '/contribute': typeof ContributeRoute
  '/explore': typeof ExploreRoute
  '/graph': typeof GraphRoute
  '/home': typeof HomeRoute
  '/insights': typeof InsightsRoute
  '/learn': typeof LearnRoute
  '/map': typeof MapRoute
  '/media': typeof MediaRoute
  '/review': typeof ReviewRoute
  '/studio': typeof StudioRoute
  '/expeditions/$id': typeof ExpeditionsIdRoute
  '/item/$id': typeof ItemIdRoute
  '/journey/$id': typeof JourneyIdRoute
  '/stations/$id': typeof StationsIdRoute
  '/expeditions/': typeof ExpeditionsIndexRoute
  '/stations/': typeof StationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ask': typeof AskRoute
  '/contribute': typeof ContributeRoute
  '/explore': typeof ExploreRoute
  '/graph': typeof GraphRoute
  '/home': typeof HomeRoute
  '/insights': typeof InsightsRoute
  '/learn': typeof LearnRoute
  '/map': typeof MapRoute
  '/media': typeof MediaRoute
  '/review': typeof ReviewRoute
  '/studio': typeof StudioRoute
  '/expeditions/$id': typeof ExpeditionsIdRoute
  '/item/$id': typeof ItemIdRoute
  '/journey/$id': typeof JourneyIdRoute
  '/stations/$id': typeof StationsIdRoute
  '/expeditions': typeof ExpeditionsIndexRoute
  '/stations': typeof StationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ask': typeof AskRoute
  '/contribute': typeof ContributeRoute
  '/explore': typeof ExploreRoute
  '/graph': typeof GraphRoute
  '/home': typeof HomeRoute
  '/insights': typeof InsightsRoute
  '/learn': typeof LearnRoute
  '/map': typeof MapRoute
  '/media': typeof MediaRoute
  '/review': typeof ReviewRoute
  '/studio': typeof StudioRoute
  '/expeditions/$id': typeof ExpeditionsIdRoute
  '/item/$id': typeof ItemIdRoute
  '/journey/$id': typeof JourneyIdRoute
  '/stations/$id': typeof StationsIdRoute
  '/expeditions/': typeof ExpeditionsIndexRoute
  '/stations/': typeof StationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ask'
    | '/contribute'
    | '/explore'
    | '/graph'
    | '/home'
    | '/insights'
    | '/learn'
    | '/map'
    | '/media'
    | '/review'
    | '/studio'
    | '/expeditions/$id'
    | '/item/$id'
    | '/journey/$id'
    | '/stations/$id'
    | '/expeditions/'
    | '/stations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ask'
    | '/contribute'
    | '/explore'
    | '/graph'
    | '/home'
    | '/insights'
    | '/learn'
    | '/map'
    | '/media'
    | '/review'
    | '/studio'
    | '/expeditions/$id'
    | '/item/$id'
    | '/journey/$id'
    | '/stations/$id'
    | '/expeditions'
    | '/stations'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ask'
    | '/contribute'
    | '/explore'
    | '/graph'
    | '/home'
    | '/insights'
    | '/learn'
    | '/map'
    | '/media'
    | '/review'
    | '/studio'
    | '/expeditions/$id'
    | '/item/$id'
    | '/journey/$id'
    | '/stations/$id'
    | '/expeditions/'
    | '/stations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AskRoute: typeof AskRoute
  ContributeRoute: typeof ContributeRoute
  ExploreRoute: typeof ExploreRoute
  GraphRoute: typeof GraphRoute
  HomeRoute: typeof HomeRoute
  InsightsRoute: typeof InsightsRoute
  LearnRoute: typeof LearnRoute
  MapRoute: typeof MapRoute
  MediaRoute: typeof MediaRoute
  ReviewRoute: typeof ReviewRoute
  StudioRoute: typeof StudioRoute
  ExpeditionsIdRoute: typeof ExpeditionsIdRoute
  ItemIdRoute: typeof ItemIdRoute
  JourneyIdRoute: typeof JourneyIdRoute
  StationsIdRoute: typeof StationsIdRoute
  ExpeditionsIndexRoute: typeof ExpeditionsIndexRoute
  StationsIndexRoute: typeof StationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute': {
      id: '/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof ContributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expeditions/': {
      id: '/expeditions/'
      path: '/expeditions'
      fullPath: '/expeditions/'
      preLoaderRoute: typeof ExpeditionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expeditions/$id': {
      id: '/expeditions/$id'
      path: '/expeditions/$id'
      fullPath: '/expeditions/$id'
      preLoaderRoute: typeof ExpeditionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/$id': {
      id: '/item/$id'
      path: '/item/$id'
      fullPath: '/item/$id'
      preLoaderRoute: typeof ItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/$id': {
      id: '/journey/$id'
      path: '/journey/$id'
      fullPath: '/journey/$id'
      preLoaderRoute: typeof JourneyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stations/': {
      id: '/stations/'
      path: '/stations'
      fullPath: '/stations/'
      preLoaderRoute: typeof StationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stations/$id': {
      id: '/stations/$id'
      path: '/stations/$id'
      fullPath: '/stations/$id'
      preLoaderRoute: typeof StationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AskRoute: AskRoute,
  ContributeRoute: ContributeRoute,
  ExploreRoute: ExploreRoute,
  GraphRoute: GraphRoute,
  HomeRoute: HomeRoute,
  InsightsRoute: InsightsRoute,
  LearnRoute: LearnRoute,
  MapRoute: MapRoute,
  MediaRoute: MediaRoute,
  ReviewRoute: ReviewRoute,
  StudioRoute: StudioRoute,
  ExpeditionsIdRoute: ExpeditionsIdRoute,
  ItemIdRoute: ItemIdRoute,
  JourneyIdRoute: JourneyIdRoute,
  StationsIdRoute: StationsIdRoute,
  ExpeditionsIndexRoute: ExpeditionsIndexRoute,
  StationsIndexRoute: StationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
